//-----------------------------------------------------------------------------
//
// See LICENSE
//
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// src/h/war_build_keymap_functions.h
// generated by src/lua/war_build_keymap_functions.lua
//-----------------------------------------------------------------------------

#ifndef WAR_BUILD_KEYMAP_FUNCTIONS_H
#define WAR_BUILD_KEYMAP_FUNCTIONS_H

#include "war_data.h"
#include "war_keymap_functions.h"

#include <string.h>

static inline void (*war_build_keymap_functions(const char* name))(war_env*) {
if (strcmp(name, "war_fat") == 0) { return war_fat; }
else if (strcmp(name, "war_thin") == 0) { return war_thin; }
else if (strcmp(name, "war_pan_follow") == 0) { return war_pan_follow; }
else if (strcmp(name, "war_goto_col") == 0) { return war_goto_col; }
else if (strcmp(name, "war_roll_cursor_goto_right_bound_or_prefix_horizontal") == 0) { return war_roll_cursor_goto_right_bound_or_prefix_horizontal; }
else if (strcmp(name, "war_goto_left_visible_bound") == 0) { return war_goto_left_visible_bound; }
else if (strcmp(name, "war_pan_center_on_cursor") == 0) { return war_pan_center_on_cursor; }
else if (strcmp(name, "war_goto_row_127") == 0) { return war_goto_row_127; }
else if (strcmp(name, "war_goto_row_60") == 0) { return war_goto_row_60; }
else if (strcmp(name, "war_clamp_cursor_row") == 0) { return war_clamp_cursor_row; }
else if (strcmp(name, "war_goto_row_0") == 0) { return war_goto_row_0; }
else if (strcmp(name, "war_pan_follow") == 0) { return war_pan_follow; }
else if (strcmp(name, "war_layer_1") == 0) { return war_layer_1; }
else if (strcmp(name, "war_layer_2") == 0) { return war_layer_2; }
else if (strcmp(name, "war_layer_3") == 0) { return war_layer_3; }
else if (strcmp(name, "war_layer_4") == 0) { return war_layer_4; }
else if (strcmp(name, "war_layer_5") == 0) { return war_layer_5; }
else if (strcmp(name, "war_layer_6") == 0) { return war_layer_6; }
else if (strcmp(name, "war_layer_7") == 0) { return war_layer_7; }
else if (strcmp(name, "war_layer_8") == 0) { return war_layer_8; }
else if (strcmp(name, "war_layer_9") == 0) { return war_layer_9; }
else if (strcmp(name, "war_layer_0") == 0) { return war_layer_0; }
else if (strcmp(name, "war_toggle_layer_1") == 0) { return war_toggle_layer_1; }
else if (strcmp(name, "war_toggle_layer_2") == 0) { return war_toggle_layer_2; }
else if (strcmp(name, "war_toggle_layer_3") == 0) { return war_toggle_layer_3; }
else if (strcmp(name, "war_toggle_layer_4") == 0) { return war_toggle_layer_4; }
else if (strcmp(name, "war_toggle_layer_5") == 0) { return war_toggle_layer_5; }
else if (strcmp(name, "war_toggle_layer_6") == 0) { return war_toggle_layer_6; }
else if (strcmp(name, "war_toggle_layer_7") == 0) { return war_toggle_layer_7; }
else if (strcmp(name, "war_toggle_layer_8") == 0) { return war_toggle_layer_8; }
else if (strcmp(name, "war_toggle_layer_9") == 0) { return war_toggle_layer_9; }
else if (strcmp(name, "war_toggle_all_layers") == 0) { return war_toggle_all_layers; }
else if (strcmp(name, "war_octave_minus_1") == 0) { return war_octave_minus_1; }
else if (strcmp(name, "war_octave_0") == 0) { return war_octave_0; }
else if (strcmp(name, "war_octave_1") == 0) { return war_octave_1; }
else if (strcmp(name, "war_octave_2") == 0) { return war_octave_2; }
else if (strcmp(name, "war_octave_3") == 0) { return war_octave_3; }
else if (strcmp(name, "war_octave_4") == 0) { return war_octave_4; }
else if (strcmp(name, "war_octave_5") == 0) { return war_octave_5; }
else if (strcmp(name, "war_octave_6") == 0) { return war_octave_6; }
else if (strcmp(name, "war_octave_7") == 0) { return war_octave_7; }
else if (strcmp(name, "war_octave_8") == 0) { return war_octave_8; }
else if (strcmp(name, "war_octave_9") == 0) { return war_octave_9; }
else if (strcmp(name, "war_octave_10") == 0) { return war_octave_10; }
else if (strcmp(name, "war_undo_save") == 0) { return war_undo_save; }
else if (strcmp(name, "war_record_midi") == 0) { return war_record_midi; }
else if (strcmp(name, "war_play_q") == 0) { return war_play_q; }
else if (strcmp(name, "war_play_w") == 0) { return war_play_w; }
else if (strcmp(name, "war_play_e") == 0) { return war_play_e; }
else if (strcmp(name, "war_play_r") == 0) { return war_play_r; }
else if (strcmp(name, "war_play_t") == 0) { return war_play_t; }
else if (strcmp(name, "war_play_y") == 0) { return war_play_y; }
else if (strcmp(name, "war_play_u") == 0) { return war_play_u; }
else if (strcmp(name, "war_play_i") == 0) { return war_play_i; }
else if (strcmp(name, "war_play_o") == 0) { return war_play_o; }
else if (strcmp(name, "war_play_p") == 0) { return war_play_p; }
else if (strcmp(name, "war_play_left_bracket") == 0) { return war_play_left_bracket; }
else if (strcmp(name, "war_play_right_bracket") == 0) { return war_play_right_bracket; }
else if (strcmp(name, "war_step_mode_fat") == 0) { return war_step_mode_fat; }
else if (strcmp(name, "war_step_mode_thin") == 0) { return war_step_mode_thin; }
else if (strcmp(name, "war_reset_step") == 0) { return war_reset_step; }
else if (strcmp(name, "war_midi_mode") == 0) { return war_midi_mode; }
else if (strcmp(name, "war_move_cursor_right") == 0) { return war_move_cursor_right; }
else if (strcmp(name, "war_move_cursor_left") == 0) { return war_move_cursor_left; }
else if (strcmp(name, "war_move_cursor_up") == 0) { return war_move_cursor_up; }
else if (strcmp(name, "war_move_cursor_down") == 0) { return war_move_cursor_down; }
else if (strcmp(name, "war_move_cursor_down_leap") == 0) { return war_move_cursor_down_leap; }
else if (strcmp(name, "war_move_cursor_up_leap") == 0) { return war_move_cursor_up_leap; }
else if (strcmp(name, "war_goto_viewport_bottom") == 0) { return war_goto_viewport_bottom; }
else if (strcmp(name, "war_goto_viewport_top") == 0) { return war_goto_viewport_top; }
else if (strcmp(name, "war_move_cursor_left_leap") == 0) { return war_move_cursor_left_leap; }
else if (strcmp(name, "war_move_cursor_right_leap") == 0) { return war_move_cursor_right_leap; }
else if (strcmp(name, "war_next_note_same_row") == 0) { return war_next_note_same_row; }
else if (strcmp(name, "war_go_to_note_end") == 0) { return war_go_to_note_end; }
else if (strcmp(name, "war_prev_note_same_row") == 0) { return war_prev_note_same_row; }
else if (strcmp(name, "war_zoom_in") == 0) { return war_zoom_in; }
else if (strcmp(name, "war_zoom_out") == 0) { return war_zoom_out; }
else if (strcmp(name, "war_zoom_reset") == 0) { return war_zoom_reset; }
else if (strcmp(name, "war_visual_mode") == 0) { return war_visual_mode; }
else if (strcmp(name, "war_visual_swap_anchor") == 0) { return war_visual_swap_anchor; }
else if (strcmp(name, "war_visual_stretch_toggle") == 0) { return war_visual_stretch_toggle; }
else if (strcmp(name, "war_undo_save") == 0) { return war_undo_save; }
else if (strcmp(name, "war_visual_move_right") == 0) { return war_visual_move_right; }
else if (strcmp(name, "war_visual_move_left") == 0) { return war_visual_move_left; }
else if (strcmp(name, "war_visual_move_up") == 0) { return war_visual_move_up; }
else if (strcmp(name, "war_visual_move_down") == 0) { return war_visual_move_down; }
else if (strcmp(name, "war_toggle_playback") == 0) { return war_toggle_playback; }
else if (strcmp(name, "war_playbar_goto_cursor") == 0) { return war_playbar_goto_cursor; }
else if (strcmp(name, "war_toggle_playbar_loop") == 0) { return war_toggle_playbar_loop; }
else if (strcmp(name, "war_playbar_goto_start") == 0) { return war_playbar_goto_start; }
else if (strcmp(name, "war_toggle_loop") == 0) { return war_toggle_loop; }
else if (strcmp(name, "war_midi_toggle") == 0) { return war_midi_toggle; }
else if (strcmp(name, "war_tap_tempo") == 0) { return war_tap_tempo; }
else if (strcmp(name, "war_toggle_across") == 0) { return war_toggle_across; }
else if (strcmp(name, "war_toggle_resample") == 0) { return war_toggle_resample; }
else if (strcmp(name, "war_toggle_crop") == 0) { return war_toggle_crop; }
else if (strcmp(name, "war_capture_audio") == 0) { return war_capture_audio; }
else if (strcmp(name, "war_capture_advance") == 0) { return war_capture_advance; }
else if (strcmp(name, "war_preview_toggle") == 0) { return war_preview_toggle; }
else if (strcmp(name, "war_set_width_to_duration") == 0) { return war_set_width_to_duration; }
else if (strcmp(name, "war_undo_save") == 0) { return war_undo_save; }
else if (strcmp(name, "war_chord_maj7") == 0) { return war_chord_maj7; }
else if (strcmp(name, "war_chord_min9") == 0) { return war_chord_min9; }
else if (strcmp(name, "war_chord_13") == 0) { return war_chord_13; }
else if (strcmp(name, "war_chord_maj11") == 0) { return war_chord_maj11; }
else if (strcmp(name, "war_chord_maj13") == 0) { return war_chord_maj13; }
else if (strcmp(name, "war_chord_min11") == 0) { return war_chord_min11; }
else if (strcmp(name, "war_chord_min13") == 0) { return war_chord_min13; }
else if (strcmp(name, "war_chord_7") == 0) { return war_chord_7; }
else if (strcmp(name, "war_chord_min7") == 0) { return war_chord_min7; }
else if (strcmp(name, "war_chord_9") == 0) { return war_chord_9; }
else if (strcmp(name, "war_chord_maj9") == 0) { return war_chord_maj9; }
else if (strcmp(name, "war_chord_6") == 0) { return war_chord_6; }
else if (strcmp(name, "war_chord_2") == 0) { return war_chord_2; }
else if (strcmp(name, "war_place_note") == 0) { return war_place_note; }
else if (strcmp(name, "war_undo_save") == 0) { return war_undo_save; }
else if (strcmp(name, "war_undo") == 0) { return war_undo; }
else if (strcmp(name, "war_redo") == 0) { return war_redo; }
else if (strcmp(name, "war_trim_note_under_cursor") == 0) { return war_trim_note_under_cursor; }
else if (strcmp(name, "war_delete_note_under_cursor") == 0) { return war_delete_note_under_cursor; }
else if (strcmp(name, "war_wave_view") == 0) { return war_wave_view; }
else if (strcmp(name, "war_yank") == 0) { return war_yank; }
else if (strcmp(name, "war_paste") == 0) { return war_paste; }
return NULL; }

#endif //WAR_BUILD_KEYMAP_FUNCTIONS_H
