//-----------------------------------------------------------------------------
//
// See LICENSE
//
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// src/h/war_build_keymap_functions.h
// generated by src/lua/war_build_keymap_functions.lua
//-----------------------------------------------------------------------------

#ifndef WAR_BUILD_KEYMAP_FUNCTIONS_H
#define WAR_BUILD_KEYMAP_FUNCTIONS_H

#include "war_data.h"
#include "war_keymap_functions.h"

#include <string.h>

static inline void (*war_build_keymap_functions(const char* name))(war_env*) {
if (strcmp(name, "war_fat") == 0) { return war_fat; }
else if (strcmp(name, "war_thin") == 0) { return war_thin; }
else if (strcmp(name, "war_pan_follow") == 0) { return war_pan_follow; }
else if (strcmp(name, "war_layer_1") == 0) { return war_layer_1; }
else if (strcmp(name, "war_layer_2") == 0) { return war_layer_2; }
else if (strcmp(name, "war_layer_3") == 0) { return war_layer_3; }
else if (strcmp(name, "war_layer_4") == 0) { return war_layer_4; }
else if (strcmp(name, "war_layer_5") == 0) { return war_layer_5; }
else if (strcmp(name, "war_layer_6") == 0) { return war_layer_6; }
else if (strcmp(name, "war_layer_7") == 0) { return war_layer_7; }
else if (strcmp(name, "war_layer_8") == 0) { return war_layer_8; }
else if (strcmp(name, "war_layer_9") == 0) { return war_layer_9; }
else if (strcmp(name, "war_layer_0") == 0) { return war_layer_0; }
else if (strcmp(name, "war_octave_minus_1") == 0) { return war_octave_minus_1; }
else if (strcmp(name, "war_octave_0") == 0) { return war_octave_0; }
else if (strcmp(name, "war_octave_1") == 0) { return war_octave_1; }
else if (strcmp(name, "war_octave_2") == 0) { return war_octave_2; }
else if (strcmp(name, "war_octave_3") == 0) { return war_octave_3; }
else if (strcmp(name, "war_octave_4") == 0) { return war_octave_4; }
else if (strcmp(name, "war_octave_5") == 0) { return war_octave_5; }
else if (strcmp(name, "war_octave_6") == 0) { return war_octave_6; }
else if (strcmp(name, "war_octave_7") == 0) { return war_octave_7; }
else if (strcmp(name, "war_octave_8") == 0) { return war_octave_8; }
else if (strcmp(name, "war_octave_9") == 0) { return war_octave_9; }
else if (strcmp(name, "war_octave_10") == 0) { return war_octave_10; }
else if (strcmp(name, "war_play_q") == 0) { return war_play_q; }
else if (strcmp(name, "war_play_w") == 0) { return war_play_w; }
else if (strcmp(name, "war_play_e") == 0) { return war_play_e; }
else if (strcmp(name, "war_play_r") == 0) { return war_play_r; }
else if (strcmp(name, "war_play_t") == 0) { return war_play_t; }
else if (strcmp(name, "war_play_y") == 0) { return war_play_y; }
else if (strcmp(name, "war_play_u") == 0) { return war_play_u; }
else if (strcmp(name, "war_play_i") == 0) { return war_play_i; }
else if (strcmp(name, "war_play_o") == 0) { return war_play_o; }
else if (strcmp(name, "war_play_p") == 0) { return war_play_p; }
else if (strcmp(name, "war_play_left_bracket") == 0) { return war_play_left_bracket; }
else if (strcmp(name, "war_play_right_bracket") == 0) { return war_play_right_bracket; }
else if (strcmp(name, "war_move_cursor_right") == 0) { return war_move_cursor_right; }
else if (strcmp(name, "war_move_cursor_left") == 0) { return war_move_cursor_left; }
else if (strcmp(name, "war_move_cursor_up") == 0) { return war_move_cursor_up; }
else if (strcmp(name, "war_move_cursor_down") == 0) { return war_move_cursor_down; }
else if (strcmp(name, "war_zoom_in") == 0) { return war_zoom_in; }
else if (strcmp(name, "war_zoom_out") == 0) { return war_zoom_out; }
else if (strcmp(name, "war_zoom_reset") == 0) { return war_zoom_reset; }
else if (strcmp(name, "war_capture_audio") == 0) { return war_capture_audio; }
else if (strcmp(name, "war_preview_toggle") == 0) { return war_preview_toggle; }
else if (strcmp(name, "war_set_width_to_duration") == 0) { return war_set_width_to_duration; }
else if (strcmp(name, "war_place_note") == 0) { return war_place_note; }
else if (strcmp(name, "war_delete_note_under_cursor") == 0) { return war_delete_note_under_cursor; }
return NULL; }

#endif //WAR_BUILD_KEYMAP_FUNCTIONS_H
