//-----------------------------------------------------------------------------
//
// See LICENSE
//
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// src/h/war_build_keymap_functions.h
// generated by src/lua/war_build_keymap_functions.lua
//-----------------------------------------------------------------------------

#ifndef WAR_BUILD_KEYMAP_FUNCTIONS_H
#define WAR_BUILD_KEYMAP_FUNCTIONS_H

#include "war_data.h"
#include "war_keymap_functions.h"

#include <string.h>

static inline void (*war_build_keymap_functions(const char* name))(war_env*) {
if (strcmp(name, "war_move_cursor_right") == 0) { return war_move_cursor_right; }
else if (strcmp(name, "war_move_cursor_left") == 0) { return war_move_cursor_left; }
else if (strcmp(name, "war_move_cursor_up") == 0) { return war_move_cursor_up; }
else if (strcmp(name, "war_move_cursor_down") == 0) { return war_move_cursor_down; }
else if (strcmp(name, "war_move_cursor_right_leap") == 0) { return war_move_cursor_right_leap; }
else if (strcmp(name, "war_move_cursor_left_leap") == 0) { return war_move_cursor_left_leap; }
else if (strcmp(name, "war_move_cursor_up_leap") == 0) { return war_move_cursor_up_leap; }
else if (strcmp(name, "war_move_cursor_down_leap") == 0) { return war_move_cursor_down_leap; }
return NULL; }

#endif //WAR_BUILD_KEYMAP_FUNCTIONS_H
